project:
  type: manuscript

execute:
  freeze: auto

format:
  typst:
    keep-typ: true
    template-partials: 
      - typst-template.typ
      - typst-show.typ
    csl: draft.csl
  html:
    comments:
      hypothesis: true
    csl: draft.csl



